version: 2
jobs:
    build:
        docker:
            - image: circleci/node:7
        steps:
            - checkout
            - run:
                name: update apt-get repo
                command: sudo apt-get update
            - run:
                name: install-dependencies
                command: sudo apt-get install -y nodejs
            - deploy:
                name: digital-ocean
                command: ssh -o "StrictHostKeyChecking no" ubuntu@34.212.23.163 "cd ~/profile-store; git pull; sudo apt-get install -y nodejs;sudo apt-get install -y npm;sudo npm install;node app.js"
    
    elasticbeanstack:
        docker:
            - image: circleci/node:7
        steps:
            - checkout
            - run:
                name: Run AWS EBS Instance
                command: ssh -o "StrictHostKeyChecking no" ubuntu@18.219.108.205 "cd ~/profile-store;git pull" |
                         echo "Installing python-pip"
                         sudo easy_install pip
                         sudo apt install python-pip
                         pip install --upgrade --user awsebcli
                         eb --version
                         echo "Creating EBS Instance"
                         eb init --platform node.js --region us-west-2 --profile test
                         eb create circleci 
  workflows:

  version: 2

  build-test-and-deploy:

    jobs:

      - build
      - elasticbeanstack