version: 2
jobs:
    build:
        docker:
            - image: circleci/node:7
        steps:
            - checkout
            #- run:
                #name: EC2-SSH
                #command: ssh -v -o ubuntu@18.220.25.125 "cd ~/profile-store; git pull; sudo apt-get install -y nodejs;sudo apt-get install -y npm;sudo npm install"
            - run:
                name: Run AWS EBS Instance
                shell: /bin/sh
                command: |
                     echo "Installing python-pip"
                     sudo easy_install pip
                     sudo apt install python-pip
                     pip install --upgrade --user awsebcli
                     
